services:
  - type: web
    name: client
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    workingDir: ./client  # Points to the client directory
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "http://localhost:3001"  # Backend URL for the client to access
    healthCheckPath: "/health"

  - type: web
    name: server
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    workingDir: ./server  # Points to the server directory
    envVars:
      - key: NODE_ENV
        value: "production"
    healthCheckPath: "/health"