services:
  # Backend service (Node.js/Express)
  - type: web
    name: server
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_BACKEND_URL
        value: "https://codecast-5du1.onrender.com"  # Updated to your backend URL
    healthCheckPath: "/"
    autoDeploy: true

  # Frontend service (React)
  - type: web
    name: client
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build"
    plan: free
    branch: main
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://codecast-5du1.onrender.com"  # Updated to your backend URL
    healthCheckPath: "/"
    autoDeploy: true